image: node:lts

pages: # The job name MUST be 'pages' for GitLab Pages to recognize it
  stage: deploy # Typically runs in the deploy stage
  script:
    - yarn install --frozen-lockfile
    - yarn predeploy # tsc -b && vite build -> dist/ (already includes public/ contents)
    - rm -rf public
    - mv dist public # GitLab Pages requires the artifact directory to be named 'public'
  artifacts:
    paths:
      - public # GitLab Pages will serve content from this directory
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
