name: Rebuild Index

on:
  release:
    types: [created]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run fetchRepo
      - run: npm run buildIndex

      # Upload the profiles.json file as an artifact
      - name: Upload profiles.json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: profiles-json
          path: ./assets/profiles.json
